import esbuild from "esbuild";
import process from "process";
import { createRequire } from 'module';
const require = createRequire(import.meta.url);
import builtins from 'builtin-modules';

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["main.ts"],
	bundle: true,
	external: ['obsidian', 
		'@codemirror/state', 
		'@codemirror/view', 
		'@codemirror/language',
		...Object.values(builtins)
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
	inject: ["./node_modules/@codemirror/state/dist/index.js"],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
